<?php
$ltmp_preset['ru']=[
	'meta'=>[
		'description'=>'Вся актуальная информация и статистика по блокчейну VIZ: блок эксплорер, делегаты, аккаунты',
	],
	'menu'=>[
		'accounts'=>'Аккаунты',
		'witnesses'=>'Делегаты',
		'explorer'=>'Блок-эксплорер',
	],
	'explorer'=>[
		'title'=>'Блок-эксплорер',
		'description'=>'Сводные данные в блокчейне VIZ, обзор блоков, транзакций, очереди делегатов, глобальные свойства системы.',

		'last_tx_caption'=>'Последние транзакции',
		'last_blocks_caption'=>'Последние блоки',

		'search_title'=>'Поиск',
		'search_description'=>'Поиск блоков и транзакций по хэшу в блокчейне VIZ.',
		'search_caption'=>'Поиск',
		'search_placeholder'=>'Поиск по номеру блока, хеш-сумме транзакции',
		'search_none'=>'По запросу «{query}» ничего не найдено. Попробуйте снова.',

		'blocks_title'=>'Блоки',
		'blocks_description'=>'Обзор последних блоков в блокчейн системе VIZ, поиск по номеру и хэшу.',
		'blocks_caption'=>'Блок',
		'blocks_data'=>'Блок {id} сформирован {date} и подписан делегатом {witness}. Содержит {trx} транзакций, {ops} операции, {vops} виртуальных операций.',
		'blocks_hash'=>'Хеш-сумма:',
		'blocks_datetime'=>'Время формирования:',
		'blocks_witness'=>'Подпись делегата:',

		'tx_title'=>'Транзакции',
		'tx_description'=>'Обзор последних транзакций в блокчейне VIZ, поиск по хэшу.',
		'tx_caption'=>'Транзакция',
		'tx_data'=>'Транзакция {hash} в блоке {block} блокчейна VIZ. Содержит {ops} операции, {vops} виртуальных операций.',
		'tx_block'=>'Блок:',
		'tx_op_virtual'=>'Виртуальная',

		'tx_table_caption'=>'Транзакции',
		'tx_table_datetime'=>'Время (GMT)',
		'tx_table_witness'=>'Делегат',
		'tx_table_trx'=>'Транзакций',
		'tx_table_num'=>'Номер',
		'tx_table_hash'=>'Хеш-сумма',
		'tx_table_ops'=>'Операций',
		'tx_table_vops'=>'Вирт. операций',

		'tx_ops_caption'=>'Операции',
		'tx_op_type'=>'Тип операции',
		'tx_op_json'=>'JSON',
		'tx_vops_caption'=>'Виртуальные операции',

		'schedule_title'=>'Очередь делегатов',
		'schedule_datetime'=>'Время формирования очереди:',
		'schedule_shuffle_block'=>'Номер блока формирования очереди:',
		'schedule_table_num'=>'Номер',
		'schedule_table_target_witness'=>'Делегат',
		'schedule_table_witness'=>'Фактический делегат',
	],
	'props_descr'=>[
		'account_creation_fee'=>'Стоимость создания аккаунта',
		'create_account_delegation_ratio'=>'Стоимость создания аккаунта делегированием',
		'create_account_delegation_time'=>'Срок делегирования при создании аккаунта',
		'bandwidth_reserve_percent'=>'Резерв пропускной способности для микроаккаунтов',
		'bandwidth_reserve_below'=>'Максимальный капитал микроаккаунта',
		'maximum_block_size'=>'Максимальный размер блока',
		'data_operations_cost_additional_bandwidth'=>'Дополнительная наценка пропускной способности за каждую data операцию в транзакции',
		'min_delegation'=>'Минимальное количество токенов при делегировании',
		'vote_accounting_min_rshares'=>'Минимальный размер награждающего капитала',
		'committee_request_approve_min_percent'=>'Минимальная доля совокупного социального капитала для решения по заявке в Фонде ДАО',
		'witness_miss_penalty_percent'=>'Штраф делегату за пропуск блока (% суммарного веса голосов за делегата)',
		'witness_miss_penalty_duration'=>'Продолжительность штрафа делегату за пропуск блока',
		'inflation_witness_percent'=>'Доля эмиссии, идущая на вознаграждение делегатов',
		'inflation_ratio_committee_vs_reward_fund_short'=>'Доля оставшейся эмиссии, идущая в Фонд ДАО',
		'inflation_ratio_committee_vs_reward_fund'=>'Доля оставшейся эмиссии, идущая в Фонд ДАО (остальное - в Фонд наград)',
		'inflation_recalc_period'=>'Срок фиксации эмиссионной модели',

		'create_invite_min_balance'=>'Минимальная сумма чека',
		'committee_create_request_fee'=>'Плата за создание заявки в Фонд ДАО',
		'create_paid_subscription_fee'=>'Плата за создание платной подписки',
		'account_on_sale_fee'=>'Плата за выставление аккаунта на продажу',
		'subaccount_on_sale_fee'=>'Плата за выставление субаккаунтов на продажу',
		'witness_declaration_fee'=>'Плата за объявление аккаунта делегатом',
		'withdraw_intervals'=>'Количество периодов (дней) уменьшения капитала',
	],
	'props_descr_type'=>[
		'account_creation_fee'=>'viz',
		'create_account_delegation_ratio'=>'делегированных viz',
		'create_account_delegation_time'=>'суток',
		'bandwidth_reserve_percent'=>'%',
		'bandwidth_reserve_below'=>'viz',
		'maximum_block_size'=>'байт',
		'data_operations_cost_additional_bandwidth'=>'%',
		'min_delegation'=>'viz',
		'vote_accounting_min_rshares'=>'viz',
		'committee_request_approve_min_percent'=>'%',
		'witness_miss_penalty_duration'=>'суток',

		'create_invite_min_balance'=>'viz',
		'committee_create_request_fee'=>'viz',
		'create_paid_subscription_fee'=>'viz',
		'account_on_sale_fee'=>'viz',
		'subaccount_on_sale_fee'=>'viz',
		'witness_declaration_fee'=>'viz',
	],
	'props_item'=>[
		'account_creation_fee'=>'viz',
		'create_account_delegation_ratio'=>'viz',
		'create_account_delegation_time'=>'сут.',
		'bandwidth_reserve_percent'=>'%',
		'bandwidth_reserve_below'=>'viz',
		'maximum_block_size'=>'байт',
		'data_operations_cost_additional_bandwidth'=>'%',
		'min_delegation'=>'viz',
		'vote_accounting_min_rshares'=>'viz',
		'committee_request_approve_min_percent'=>'%',
		'witness_miss_penalty_percent'=>'%',
		'witness_miss_penalty_duration'=>'сут.',
		'inflation_recalc_period'=>'сут.',
		'inflation_witness_percent'=>'%',
		'inflation_ratio_committee_vs_reward_fund'=>'%',

		'create_invite_min_balance'=>'viz',
		'committee_create_request_fee'=>'viz',
		'create_paid_subscription_fee'=>'viz',
		'account_on_sale_fee'=>'viz',
		'subaccount_on_sale_fee'=>'viz',
		'witness_declaration_fee'=>'viz',
		'withdraw_intervals'=>'',
	],
	'witnesses'=>[
		'title'=>'Делегаты',
		'description'=>'Таблица делегатов блокчейна VIZ',
		'personal_description'=>'Статистика и информация по делегату {witness} в блокчейне VIZ',
		'inactive'=>'Неактивные',
		'addon_col'=>'Дополнительный столбец:',
		'col_penalty'=>'Штраф',
		'col_blocks'=>'Блоков',
		'col_total_missed'=>'Пропусков',
		'col_rewards'=>'Награда',
		'col_prop'=>'Параметр:',

		'witness'=>'Делегат',
		'votes'=>'Вес голосов',
		'votes_descr'=>'Суммарный передаваемый вес голосов от участников сети',
		'version'=>'Версия',
		'version_descr'=>'Используемая версия протокола',
		'penalty'=>'Штраф',
		'penalty_descr'=>'Штраф за пропущенные блоки влияют на учитываемый вес голосов',
		'blocks'=>'Блоков',
		'blocks_descr'=>'Количество подписанных блоков',
		'total_missed'=>'Пропусков',
		'total_missed_descr'=>'Количество пропущенных блоков',
		'rewards'=>'Награда',
		'rewards_descr'=>'Сумма полученных наград за подписание блоков',
		'prop'=>'Параметр',

		'url'=>'Заявление делегата',
		'key'=>'Ключ подписи',
		'status'=>'Статус',
		'status_disabled'=>'отключен',
		'sum_votes'=>'Суммарный вес полученных голосов',
		'voter_list'=>'Список проголосовавших',
		'vote_weight'=>'вес голоса:',
		'voted_props'=>'Голосуемые параметры',
		'emission_distribution'=>'Распределение эмиссии',
		'reward_fund'=>'Фонд наград',
		'dao_fund'=>'Фонд ДАО',
		'witnesses_fund'=>'Фонд делегатов',
	],
	'accounts'=>[
		'title'=>'Аккаунты',
		'description'=>'Таблица аккаунтов в блокчейне VIZ',
		'personal_description'=>'Информация по аккаунту {account} в блокчейне VIZ',
		'full_personal_description'=>'Карточка аккаунта @{account} в блокчейне VIZ: история операций, социальный капитал, делегирование, публичные ключи, голоса за делегатов.',
		'account'=>'Аккаунт',
		'avatar'=>'Аватар',
		'nickname'=>'Псевдоним',
		'about'=>'Об аккаунте',
		'empty_about'=>'Отсутствует описание аккаунта',
		'location'=>'Местоположение',
		'site'=>'Сайт',
		'mail'=>'Электронная почта',
		'interests'=>'Интересы:',
		'services'=>'Контакты:',

		'services_facebook'=>'Facebook',
		'services_instagram'=>'Instagram',
		'services_twitter'=>'Twitter',
		'services_vk'=>'Вконтакте',
		'services_telegram'=>'Telegram',
		'services_skype'=>'Skype',
		'services_viber'=>'Viber',
		'services_whatsapp'=>'WhatsApp',

		'created'=>'Создан:',
		'genesis'=>'генезис',

		'receiver_awards'=>'Получено наград:',
		'benefactor_awards'=>'Получено бенефициарских:',
		'keys_type_1'=>'Мастер',
		'keys_type_2'=>'Активный',
		'keys_type_3'=>'Регулярный',
		'keys_type_4'=>'Мемо',

		'public_keys'=>'Публичные ключи',
		'authority_type'=>'Тип доступа',
		'public_key'=>'Публичный ключ',
		'weight_threshold'=>'Вес / Необходимый',

		'authority_type_1'=>'Мастер доступ',
		'authority_type_2'=>'Активный доступ',
		'authority_type_3'=>'Регулярный доступ',

		'delegated_authority'=>'Доверенные аккаунты',
		'assets'=>'Активы',
		'capital'=>'Капитал (viz)',
		'balance'=>'Кошелёк (viz)',
		'energy'=>'Энергия (%)',
		'withdraw_enabled'=>'Включено уменьшение',
		'income_delegation'=>'Входящее делегирование',
		'outcome_delegation'=>'Исходящее делегирование',
		'delegations'=>'Делегирование',
		'delegations_account'=>'Аккаунт',
		'delegations_amount'=>'Капитал (viz)',
		'delegations_reclaimed'=>'Отозвано',

		'dao'=>'ДАО',
		'dao_witness'=>'Делегат:',
		'dao_witness_yes'=>'Да',
		'dao_witness_no'=>'Нет',
		'dao_witness_vote_weight'=>'Вес голоса за делегата:',
		'dao_witness_votes'=>'Список голосов за делегатов:',
		'dao_witness_votes_empty'=>'Голоса за делегатов: <span class="red">Отсутствуют</span>',

		'history'=>'История операций',
		'history_types_accounts'=>'Аккаунты',
		'history_types_capital'=>'Капитал',
		'history_types_transfers'=>'Переводы',
		'history_types_rewards'=>'Награды',
		'history_types_dao'=>'ДАО',
		'history_types_subscriptions'=>'Подписки',
		'history_types_all'=>'Все',
		'history_search'=>'Поиск',

		'history_date'=>'Время (GMT)',
		'history_op'=>'Операция',
		'history_descr'=>'Описание',

		'history_load_more'=>'Показать больше записей&hellip;',

		'count_all'=>'Всего аккаунтов:',
		'count_with_assets'=>'Из них имеют токены viz:',
		'search_login'=>'Имя аккаунта',
		'effective_capital_description'=>'Действующий социальный капитал с учетом делегированного исходящего и входящего капиталов',
		'effective_capital'=>'Действующий капитал',
		'self_capital'=>'Собственный капитал',
		'balance'=>'Кошелёк',
		'balance_description'=>'Баланс переносимых токенов VIZ',
		'summary'=>'Сумма',
		'summary_description'=>'Сумма собственного капитала и токенов',

		'empty_result'=>'Ничего не найдено, попробуйте задать другие условия для поиска.',
		'prev_page'=>'&larr; Предыдущая страница',
		'next_page'=>'Следующая страница &rarr;',
	],
	'index'=>[
		'title'=>'Главная',
		'witnesses_props'=>'Делегатские параметры',
		'witnesses_props_name'=>'Параметр',
		'witnesses_props_value'=>'Значение',
		'state_title'=>'Состояние блокчейна VIZ',//State of the VIZ blockchain
		'state_date'=>'на',//as of

		'activity'=>'Активность',

		'chart_amount'=>'Количество',
		'chart_accounts_amount'=>'Количество активных аккаунтов',
		'chart_in_30_days'=>'за 30 дней',
		'chart_in_7_days'=>'за 7 дней',
		'chart_in_1_day'=>'за 1 день',
		'chart_trx_amount'=>'Количество транзакций',
		'chart_per_day'=>'за сутки',

		'period'=>'Период',
		'accounts'=>'Аккаунты',
		'in_30_days'=>'За 30 дней',
		'in_7_days'=>'За 7 дней',
		'in_1_day'=>'За 1 день',
		'in_1_hour'=>'За 1 час',
		'blocks'=>'Блоки',
		'value'=>'Значение',
		'average_block_size'=>'Средний размер блока',
		'block_filling'=>'Заполнение блока',
		'trx_count'=>'Транзакций за сутки',
		'network_accessibility'=>'Доступность сети',
		'bandwidth_limitation'=>'Ограничение пропускной способности',

		'economy'=>'Экономика',//the
		'tokens'=>'Токены',
		'amount'=>'Количество, viz',
		'liquid'=>'Ликвидные',
		'in_capital'=>'В капитале',
		'dao_fund'=>'Фонд ДАО',
		'reward_fund'=>'Фонд наград',
		'total'=>'Всего в экономике',
		'freezed'=>'Замороженные',
		'summary'=>'Всего',

		'emission'=>'Эмиссия',
		'witnesses'=>'Делегаты',
		'fixation_period'=>'Срок фиксации',
		'days'=>'сут.',
		'recalculation'=>'Пересчёт распределения',//Distribution recalculation
		'total_per_year'=>'Всего в год',

		'prop_title'=>'Параметр',
		'prop_value_range'=>'Значение для диапазона блоков',
		'prop_witnesses_values'=>'Параметры делегатов',
		'prop_table_witness'=>'Делегат',
		'prop_table_name'=>'Параметр',
		'prop_change_dynamics'=>'Динамика изменений',
		'prop_table_time'=>'Время',
		'prop_table_value'=>'Значение',

		'error'=>'Ошибка',
		'page_not_found'=>'Страница не найдена.',
	],
	'ops-history'=>[
		'award_to'=>'Награждение <a class="view-account" href="/accounts/{receiver}/">{receiver}</a> на <span class="view-percent">{energy}%</span>',
		'award_from'=>'Получена награда от <a class="view-account" href="/accounts/{initiator}/">{initiator}</a> на <span class="view-percent">{energy}%</span>',
		'award_memo'=>' с заметкой ',
		'benefactor_award'=>'Получена бенефициарская награда <span class="view-tokens">{shares}</span> от <a class="view-account" href="/accounts/{initiator}/">{initiator}</a>',
		'benefactor_award_empty'=>'Получена пустая бенефициарская награда от <a class="view-account" href="/accounts/{initiator}/">{initiator}</a>',
		'receive_award'=>'<span class="view-tokens">{shares}</span> получено в награду от <a class="view-account" href="/accounts/{initiator}/">{initiator}</a>',
		'account_metadata'=>'Обновлен публичный профиль',
		'account_create'=>'Создан аккаунт <a class="view-account" href="/accounts/{account}/">{account}</a>',
		'account_create_tokens'=>' с передачей в социальный капитал <span class="view-tokens">{tokens}</span>',
		'account_create_delegation'=>', делегировано <span class="view-tokens">{shares}</span>',
		'create_invite'=>'Выписан чек на <span class="view-tokens">{tokens}</span> с кодом проверки <span class="view-key">{key}</span>',
		'claim_invite_balance'=>'Погашен чек с кодом <span class="view-key">{key}</span>',
		'use_invite_balance'=>'Погашен чек с кодом <span class="view-key">{key}</span>',
		'transfer_from'=>'<span class="view-tokens">{tokens}</span> отправлено <a class="view-account" href="/accounts/{to}/">{to}</a>',
		'transfer_to'=>'<span class="view-tokens">{tokens}</span> получено от <a class="view-account" href="/accounts/{from}/">{from}</a>',
		'transfer_memo'=>' с заметкой ',
		'transfer_to_vesting_from'=>'<span class="view-tokens">{tokens}</span> отправлено в социальный капитал <a class="view-account" href="/accounts/{to}/">{to}</a>',
		'transfer_to_vesting_to'=>'<span class="view-tokens">{tokens}</span> получено в социальный капитал от <a class="view-account" href="/accounts/{from}/">{from}</a>',
		'withdraw_vesting'=>'Начато уменьшение социального капитала на <span class="view-tokens">{shares}</span>',
		'withdraw_vesting_stop'=>'Остановлено уменьшение социального капитала',
		'fill_vesting_withdraw'=>'<span class="view-tokens">{tokens}</span> получено от уменьшения социального капитала',
		'fill_vesting_withdraw_from'=>'Аккаунту <a class="view-account" href="/accounts/{to}/">{to}</a> отправлено <span class="view-tokens">{tokens}</span> от понижения социального капитала',
		'fill_vesting_withdraw_to'=>'<span class="view-tokens">{tokens}</span> получено от уменьшения социального капитала аккаунтом <a class="view-account" href="/accounts/{from}/">{from}<a>',
		'delegate_vesting_shares_from'=>'<span class="view-tokens">{shares}</span> получено делегированием от <a class="view-account" href="/accounts/{from}/">{from}</a>',
		'delegate_vesting_shares_to'=>'<span class="view-tokens">{shares}</span> делегировано аккаунту <a class="view-account" href="/accounts/{to}/">{to}</a>',
		'delegate_vesting_shares_from_stop'=>'Отмена делегирования от <a class="view-account" href="/accounts/{from}/">{from}</a>',
		'delegate_vesting_shares_to_stop'=>'Отмена делегирования для <a class="view-account" href="/accounts/{to}/">{to}</a>',
		'return_vesting_delegation'=>'<span class="view-tokens">{shares}</span> возвращено в социальный капитал из делегирования',


		'committee_worker_create_request'=>'Создание заявки в фонд ДАО, воркер <a class="view-account" href="/accounts/{worker}/">{worker}</a>, запрашиваемая сумма <span class="view-tokens">{tokens}</span>, длительность <span class="view-date">{days} дней</span>, <span class="view-memo" data-text="{text}">информация</span>',
		'committee_worker_cancel_request'=>'Отмена заявки №{request_id} в фоне ДАО',
		'committee_vote_request'=>'Голос на <span class="view-percent">{percent}%</span> по заявке №{request_id} в фонд ДАО',
		'committee_pay_request'=>'Выплата <span class="view-tokens">{tokens}</span> из фонда ДАО по заявке  №{request_id}',

		'account_update'=>'Обновление прав доступа',

		'set_subaccount_price'=>'Выставление на продажу субаккаунтов за <span class="view-tokens">{tokens}</span>, бенефициар <a class="view-account" href="/accounts/{seller}/">{seller}</a>',
		'set_subaccount_price_stop'=>'Остановка продажи субаккаунтов',
		'set_account_price'=>'Аккаунт <a class="view-account" href="/accounts/{account}/">{account}</a> выставлен на продажу за <span class="view-tokens">{tokens}</span>, бенефициар <a class="view-account" href="/accounts/{seller}/">{seller}</a>',
		'set_account_price_stop'=>'Снятие аккаунта с продажи',
		'account_sale'=>'<a class="view-account" href="/accounts/{buyer}/">{buyer}</a> заплатил <span class="view-tokens">{tokens}</span> <a class="view-account" href="/accounts/{seller}/">{seller}</a> за покупку аккаунта <a class="view-account" href="/accounts/{account}/">{account}</a>',
		'buy_account'=>'Покупка аккаунта <a class="view-account" href="/accounts/{account}/">{account}</a> за <span class="view-tokens">{tokens}</span>, переведено в капитал <span class="view-tokens">{tokens_to_shares}</span>',

		'shutdown_witness'=>'Отключение делегата',
		'witness_update'=>'Включение делегата, ключ подписи <span class="view-key">{key}</span>, <span class="view-memo" data-text="{text}">информация</span>',
		'witness_update_stop'=>'Отключение делегата',

		'account_witness_vote'=>'Голос за делегата <a class="view-account" href="/witnesses/{witness}/">{witness}</a>',
		'account_witness_vote_stop'=>'Снят голос с делегата <a class="view-account" href="/witnesses/{witness}/">{witness}</a>',

		'account_witness_vote_income'=>'<a class="view-account" href="/accounts/{account}/">{account}</a> проголосовал за делегата',
		'account_witness_vote_income_stop'=>'<a class="view-account" href="/accounts/{account}/">{account}</a> снял голос с делегата',
		'paid_subscription_action_to'=>'Оплата подписки на <a class="view-account" href="/accounts/{account}/">{account}</a>, уровень {level}, стоимость подписки <span class="view-tokens">{summary_amount}</span>',
		'paid_subscription_action_from'=>'Оплата подписки от <a class="view-account" href="/accounts/{subscriber}/">{subscriber}</a>, уровень {level}, стоимость подписки <span class="view-tokens">{summary_amount}</span>',


		'cancel_paid_subscription_to'=>'Завершение подписки на <a class="view-account" href="/accounts/{account}/">{account}</a>',
		'cancel_paid_subscription_from'=>'Завершение подписки от <a class="view-account" href="/accounts/{subscriber}/">{subscriber}</a>',

		'paid_subscribe_to'=>'Оформлена подписка на <a class="view-account" href="/accounts/{account}/">{account}</a>, уровень {level}, суммарная стоимость подписки <span class="view-tokens">{summary_amount}</span>',
		'paid_subscribe_from'=>'Оформлена подписка от <a class="view-account" href="/accounts/{subscriber}/">{subscriber}</a>, уровень {level}, суммарная стоимость подписки <span class="view-tokens">{summary_amount}</span>',
		'paid_subscribe_auto_renewal'=>' (включено автопродление)',

		'set_paid_subscription'=>'Создание платной подписки, <a href="{link}">условия</a>, максимальный уровень: {levels}, стоимость за уровень: {amount}, период действия подписки (количество дней): {period}',
		'invite_registration'=>'Регистрация по инвайт-коду <span class="view-key">{key}</span>',
	],
];